SpaceShop/Models/Kindergarten/KindergartenCreateUpdateViewModel.cs
namespace SpaceShop.Models.Kindergarten
{
    public class KindergartenCreateUpdateViewModel
    {
     public Guid? Id { get; set; }
     public string GroupName { get; set; }
     
        public int ChildrenCount { get; set; }

        public string KindergartenName { get; set; }
        public string Teacher { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }

    }
}

SpaceShop/Models/Kindergarten/KindergartenDeleteViewModel.cs
namespace SpaceShop.Models.Kindergarten
{
    public class KindergartenDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }

        public int ChildrenCount { get; set; }

        public string KindergartenName { get; set; }
        public string Teacher { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

SpaceShop/Models/Kindergarten/KindergartenDetailsViewModel.cs
namespace SpaceShop.Models.Kindergarten
{
    public class KindergartenDetailsViewModel {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }

        public int ChildrenCount { get; set; }

        public string KindergartenName { get; set; }
        public string Teacher { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

SpaceShop/Models/Kindergarten/KindergartenIndexViewModel.cs
namespace SpaceShop.Models.Kindergarten
{
    public class KindergartenIndexViewModel {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }

        public int ChildrenCount { get; set; }

        public string KindergartenName { get; set; }
        public string Teacher { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

SpaceShop/Controllers/KindergartenController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.ApplicationServices.Services;
using Shop.Core.Domain;
using Shop.Core.ServiceInterface;
using Shop.Core.Dto;
using Shop.Data;
using SpaceShop.Models.Kindergarten;
using Microsoft.AspNetCore.Authorization;


namespace SpaceShop.Controllers
{
    //[Authorize]
    public class KindergartenController : Controller
    {
       

            private readonly ShopContext _context;
            private readonly IKindergartenServices _kindergartenServices;



            public KindergartenController
                (
                    ShopContext context,
                    IKindergartenServices kindergartenServices
                )
            {
                _context = context;
                _kindergartenServices = kindergartenServices;
            }


            [HttpGet]
            public IActionResult Index()
            {
                var result = _context.Kindergartens
                    .OrderByDescending(y => y.CreatedAt)
                    .Select(x => new KindergartenIndexViewModel
                    {
                        Id = x.Id,
                        GroupName = x.GroupName,
                        Teacher = x.Teacher,
                        ChildrenCount = x.ChildrenCount,
                        KindergartenName=x.KindergartenName,
                    });

                return View(result);
            }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var kindergarten = await _kindergartenServices.GetAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }


            var vm = new KindergartenDetailsViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.ModifiedAt = kindergarten.ModifiedAt;

            return View(vm);
        }

        [HttpGet]
            public IActionResult Create()
            {
                KindergartenCreateUpdateViewModel vm = new();

                return View("CreateUpdate", vm);
            }


            [HttpPost]
            public async Task<IActionResult> Create(KindergartenCreateUpdateViewModel vm)
            {
                var dto = new KindergartenDto()
                {

          
                    Id = vm.Id,
                    GroupName = vm.GroupName ,
                    ChildrenCount = vm.ChildrenCount,
                    KindergartenName = vm.KindergartenName,
                    Teacher = vm.Teacher,
                    CreatedAt = vm.CreatedAt,
                    ModifiedAt = vm.ModifiedAt,
                    
                };

                var result = await _kindergartenServices.Create(dto);

                if (result == null)
                {
                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Index), vm);
            }

            [HttpGet]
            public async Task<IActionResult> Update(Guid id)
            {
                var kindergarten = await _kindergartenServices.GetAsync(id);

                if (kindergarten == null)
                {
                    return NotFound();
                }

                var vm = new  KindergartenCreateUpdateViewModel ();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.ModifiedAt = kindergarten.ModifiedAt;
           


                return View("CreateUpdate", vm);
            }

            [HttpPost]
            public async Task<IActionResult> Update(KindergartenCreateUpdateViewModel vm)
            {

            var dto = new KindergartenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                
            };
            //var dto = new KindergartenDto();

            //dto.Id = vm.Id;
            //dto.GroupName = vm.GroupName;
            //dto.ChildrenCount = vm.ChildrenCount;
            //dto.KindergartenName = vm.KindergartenName;
            //dto.Teacher = vm.Teacher;
            //dto.CreatedAt = vm.CreatedAt;
            //dto.ModifiedAt = vm.ModifiedAt;

            var result = await _kindergartenServices.Update(dto);

                if (result == null)
                {
                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Index), vm);
            }

            [HttpGet]
            public async Task<IActionResult> Delete(Guid id)
            {
                var kindergarten = await _kindergartenServices.GetAsync(id);

                if (kindergarten == null)
                {
                    return NotFound();
                }

                var vm = new KindergartenDeleteViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.ModifiedAt = kindergarten.ModifiedAt;

            return View(vm);
            }


            [HttpPost]
            public async Task<IActionResult> DeleteConfirmation(Guid id)
            {
                var kindergartenId = await _kindergartenServices.Delete(id);

                if (kindergartenId == null)
                {
                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Index));
            }

    }
}

SpaceShop/Views/Kindergarten/CreateUpdate.cshtml
@model SpaceShop.Models.Kindergarten.KindergartenCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}


<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label">Group Name</label>
            <div class="col-sm-10">
                <input asp-for="GroupName" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount"  class="col-sm-2 col-form-label">Children Count</label>
            <div class="col-sm-10">
                <input asp-for="ChildrenCount" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label">Kindergarten Name</label>
            <div class="col-sm-10">
                <input asp-for="KindergartenName" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"> Teacher</label>
            <div class="col-sm-10">
                <input asp-for="Teacher" class="form-control" />
            </div>
        </div>


        <hr />
        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="Kindergarten" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="Kindergarten" type="submit" class="btn btn-primary" value="Create" />
        }
        

        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

SpaceShop/Views/Kindergarten/Delete.cshtml
@model SpaceShop.Models.Kindergarten.KindergartenDeleteViewModel


<h1>Delete</h1>

<div>

    <h4>Kindergarten</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.GroupName)
        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ChildrenCount)
        </div>

        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.KindergartenName)
        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Teacher)
        </div>

       

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>

    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="Kindergarten" class="btn btn-success">Back</a>
    </form>
</div>

SpaceShop/Views/Kindergarten/Details.cshtml
@model SpaceShop.Models.Kindergarten.KindergartenDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Kindergarten</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.GroupName)
        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ChildrenCount)
        </div>

        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.KindergartenName)
        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Teacher)
        </div>



        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>


    </dl>
    <a asp-action="Index" asp-controller="Kindergarten" class="btn btn-danger">Index</a>
</div>

SpaceShop/Views/Kindergarten/Index.cshtml
@model IEnumerable<SpaceShop.Models.Kindergarten.KindergartenIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="Create" asp-controller="Kindergarten" type="submit" class="btn btn-primary">Create</a>
</div>


<div class="h1">
    Kindergarten
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">GroupName</th>
                <th scope="col">ChildrenCount</th>
                <th scope="col">KindergartenName</th>
                <th scope="col">Teacher</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var kindergarten in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@kindergarten.GroupName</td>
                    <td>@kindergarten.ChildrenCount</td>
                    <td>@kindergarten.KindergartenName</td>
                    <td>@kindergarten.Teacher</td>
                    <td>
                        <a asp-action="details" asp-controller="Kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="Kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="Kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber += 1;
            }
        </tbody>
    </table>
</form>