SpaceShop/Controllers/ChuckNorrisController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Core.Dto.ChuckNorris;
using Shop.Core.Dto.OpenWeatherDto;
using Shop.Core.ServiceInterface;
using SpaceShop.Models.ChuckNorris;
using SpaceShop.Models.OpenWeathers;

namespace SpaceShop.Controllers
{
    public class ChuckNorrisController : Controller
    {


        private readonly IChuckNorrisServices _chuckNorrisServices;

        public ChuckNorrisController(IChuckNorrisServices chuckNorrisServices)
        {
            _chuckNorrisServices = chuckNorrisServices;

        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Chuck()
        {

            return RedirectToAction(nameof(Search));
        }

        [HttpGet]

        public IActionResult Search()
        {
            ChuckNorrisResultDto dto=new ChuckNorrisResultDto();

            _chuckNorrisServices.ChuckNorrisResult(dto);
            ChuckNorrisViewModel vm = new();

            vm.Categories= dto.Categories ;
            vm.UpdatedAt = dto.UpdatedAt ;
            vm.CreatedAt = dto.CreatedAt ;
            vm.IconUrl = dto.IconUrl ;
            vm.Id = dto.Id ;
            vm.Url = dto.Url ;
            vm.Value = dto.Value ;

          

            return View(vm);

        }
     
    }
}

SpaceShop/Controllers/EmailController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Core.Dto.Email;
using Shop.Core.ServiceInterface;
using SpaceShop.Models.Email;

namespace SpaceShop.Controllers
{
    //[Authorize]
    public class EmailController : Controller
    {
            private readonly IEmailService _emailService;
            public EmailController(IEmailService emailService)
            {
                _emailService = emailService;


            }

            [HttpGet]
            public IActionResult Index()
            {
                return View();

            }

            [HttpPost]
            public IActionResult SendEmail(EmailViewModel vm)
            {
                EmailDto dto = new EmailDto();
                dto.To = vm.To;
                dto.Subject = vm.Subject;
                dto.Body = vm.Body;

                _emailService.sendEmail(dto);



                return RedirectToAction(nameof(Index)); ;
            }
        }
    }

SpaceShop/Controllers/PagesController.cs
using Microsoft.AspNetCore.Mvc;
using SpaceShop.Models;
using System.Diagnostics;

namespace SpaceShop.Controllers
{
    public class PagesController : Controller
    {

        private readonly ILogger<PagesController> _logger;

        public PagesController(ILogger<PagesController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
      
    }
}

SpaceShop/Controllers/RealEstateController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.ApplicationServices.Services;
using Shop.Core.Dto;
using Shop.Core.ServiceInterface;
using Shop.Data;
using Microsoft.EntityFrameworkCore;
using SpaceShop.Models.RealEstate;

using System.Net.NetworkInformation;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.AspNetCore.Authorization;

namespace SpaceShop.Controllers
{
    //[Authorize]
    public class RealEstateController : Controller
    {

        private readonly ShopContext _context;
        private readonly IRealEstateServices _realEstatesServices;
        private readonly IFileServices _fileServices;



        public RealEstateController
            (
                ShopContext context,
                IRealEstateServices realEstates,
                IFileServices fileservices
       

       
            )
        {
            _context = context;
            _realEstatesServices = realEstates;
            _fileServices = fileservices;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var result = _context.RealEstates
                .OrderByDescending(y => y.CreatedAt)
                .Select(x => new RealEstateIndexViewModel
                {
                    Id = x.Id,
                    Address = x.Address,
                    BuildingType = x.BuildingType,
                    RoomCount = x.RoomCount,
                    SizeSqrM = x.SizeSqrM
                });

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
               .Where(x => x.RealEstateId == id)
               .Select(y => new ImageToDatabaseViewModel
               {
                   RealEstateId = y.Id,
                   ImageId = y.Id,
                   ImageData = y.ImageData,
                   ImageTitle = y.ImageTitle,
                   Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
               }).ToArrayAsync();

            var vm = new RealEstateDetailsViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel vm = new();

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Address = vm.Address,
                SizeSqrM = vm.SizeSqrM,
                RoomCount = vm.RoomCount,
                Floor = vm.Floor,
                BuildingType = vm.BuildingType,
                BuiltInYear = vm.BuiltInYear,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image.Select(x => new FileToDatabaseDto
                {
                    Id = x.ImageId,
                    ImageData = x.ImageData,
                    ImageTitle = x.ImageTitle,
                    RealEstateID = x.RealEstateId

                }).ToArray()
            };

            var result = await _realEstatesServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos= await _context.FileToDatabases
                .Where(x=> x.RealEstateId==id)
                .Select(y=>new ImageToDatabaseViewModel
                {
                    RealEstateId=y.Id,
                    ImageId=y.Id,
                    ImageData=y.ImageData,
                    ImageTitle=y.ImageTitle,
                    Image=string.Format("data:image/gif;base64,{0}",Convert.ToBase64String(y.ImageData))

            }).ToArrayAsync();

            var vm = new RealEstateCreateUpdateViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.Image.AddRange(photos);


            return View("CreateUpdate", vm);
        }


        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto();

            dto.Id = vm.Id;
            dto.Address = vm.Address;
            dto.SizeSqrM = vm.SizeSqrM;
            dto.RoomCount = vm.RoomCount;
            dto.Floor = vm.Floor;
            dto.BuildingType = vm.BuildingType;
            dto.BuiltInYear = vm.BuiltInYear;
            dto.CreatedAt = vm.CreatedAt;
            dto.UpdatedAt = vm.UpdatedAt;
            dto.Files = vm.Files;
            dto.Image = vm.Image.Select(x => new FileToDatabaseDto
            {
                Id = x.ImageId,
                ImageData = x.ImageData,
                ImageTitle = x.ImageTitle,
                RealEstateID = x.RealEstateId

            }).ToArray();
           

        var result = await _realEstatesServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }
            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new ImageToDatabaseViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))

                }).ToArrayAsync();

            var vm = new RealEstateDeleteViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.ImageToDatabase.AddRange(photos);


            return View(vm);

        }


        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var realEstateId = await _realEstatesServices.Delete(id);

            if (realEstateId == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task <IActionResult>RemoveImage(ImageToDatabaseViewModel file)
        {
            var dto = new FileToDatabaseDto()
            {
               
                Id=file.ImageId
            };

            var image=await _fileServices.RemoveImageFromDatabase(dto);


            if (image == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));

        }


        [HttpPost]
        public async Task<IActionResult>RemoveImages(Guid id)
        {

            var realEstate = await _realEstatesServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }
            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new ImageToDatabaseViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))

                }).ToArrayAsync();

            var vm = new RealEstateDeleteViewModel();

          
            vm.ImageToDatabase.AddRange(photos);


            return View(vm);


        }
    }
}
// teha meetod ,mis kustutab mitu piltu korraga ara

SpaceShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<Shop.Core.Domain.ApplicationUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpaceShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SpaceShop.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SpaceShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spaceships" asp-action="Index">Spaceships</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RealEstate" asp-action="Index">RealEstate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kindergarten" asp-action="Index">Kindergarten</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OpenWeathers" asp-action="Index">OpenWeathers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChuckNorris" asp-action="Index">ChuckNorris</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cocktail" asp-action="Index">Cocktail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AccuWeather" asp-action="Index">AccuWeather</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="Index">Email</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pages" asp-action="Index">Message</a>
                        </li>
                        
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown">
                                <div class="dropdown">
                                    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                        Manage Account
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li><a class="dropdown-item" asp-controller="Accounts" asp-action="ResetPassword">Reset password</a></li>
                                        <li><a class="dropdown-item" asp-controller="Accounts" asp-action="ChangePassword"> Change password</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Accounts" asp-action="Logout">
                            <button type="submit" class="nav-link btn btn-link py-0" style="width:auto; padding-top: 0.8 rem;">
                                Logout @User.Identity.Name
                            </button>

                            </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text -dark" asp-controller="Accounts" asp-action="Register">Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text -dark" asp-controller="Accounts" asp-action="Login">Login</a>
                            </li>
                        }
                    @* </ul>
                    <ul class="navbar-nav ml-auto"> 
                        <li class="nav-item">
                            <a class="nav-link text -dark"asp-controller="Accounts" asp-action="Register" >Register</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text -dark" asp-controller="Accounts" asp-action="Login">Login</a>
                        </li>
                    </ul> *@

                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023  Copywright SpaceShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy </a>
            <a asp-area="" asp-controller="Home" asp-action="Spaceships">Spaceships </a>
            <a asp-area="" asp-controller="Home" asp-action="RealEstate">RealEstate </a>
            <a asp-area="" asp-controller="Home" asp-action="Kindergarten">Kindergarten </a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>